// <auto-generated />
namespace Keboola.Bot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renameTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201702021242421_renameTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
